<a href="https://colab.research.google.com/github/2025cssumankumarig-cpu/dav_lab1/blob/main/4NI25CS201_EXP_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
print("numpy version:",np.__version__)
print("pandas version:",np.__version__)
marks=np.array([78,85,92,67,88])
print("marks:",marks)
print(type(marks))
print("number of dimensions:",marks.ndim)
print("shape:",marks.shape)
print("number of elements:",marks.size)
print("original:",marks)
print("add 5:",marks+5)
print("multiply by 2:",marks*2)
print("divide by 2:",marks/2)
print("sum:",marks.sum())
print("mean:",marks.mean())
print("maximun:",marks.max())
print("minimum:",marks.min())
print("first marks:",marks[0])
print("second marks:",marks[1])
print("last marks:",marks[-1])
print("index 1 to 3:",marks[1:4])
print("first three:",marks[:3])
print("from index 2:",marks[2:])
print("increment by 2:",marks[::2])

numpy version: 2.0.2
pandas version: 2.0.2
marks: [78 85 92 67 88]
<class 'numpy.ndarray'>
number of dimensions: 1
shape: (5,)
number of elements: 5
original: [78 85 92 67 88]
add 5: [83 90 97 72 93]
multiply by 2: [156 170 184 134 176]
divide by 2: [39.  42.5 46.  33.5 44. ]
sum: 410
mean: 82.0
maximun: 92
minimum: 67
first marks: 78
second marks: 85
last marks: 88
index 1 to 3: [85 92 67]
first three: [78 85 92]
from index 2: [92 67 88]
increment by 2: [78 92 88]

In [ ]:
student_marks=np.array([
    [75,85,92],[45,56,75],[34,45,76]
])
print(student_marks)
print("shape:",student_marks.shape)
print("mean of all values:",student_marks.mean())
print("column-wise mean:",student_marks.mean(axis=0))
print("row-wise mean:",student_marks.mean(axis=1))

[[75 85 92]
 [45 56 75]
 [34 45 76]]
shape: (3, 3)
mean of all values: 64.77777777777777
column-wise mean: [51.33333333 62.         81.        ]
row-wise mean: [84.         58.66666667 51.66666667]

In [ ]:
data={
    "name":["anu","priya","sita","ram"],
    "branch":["cse","cse","ai/ml","cse"],
    "marks":[34,56,24,56]
}
df=pd.DataFrame(data)
print(df)
print("shape:",df.shape)
print("\ncolumns:",df.columns)
print(df.head())
print(df.tail())
print(df.info())
print(df.describe())

    name branch  marks
0    anu    cse     34
1  priya    cse     56
2   sita  ai/ml     24
3    ram    cse     56
shape: (4, 3)

columns: Index(['name', 'branch', 'marks'], dtype='object')
    name branch  marks
0    anu    cse     34
1  priya    cse     56
2   sita  ai/ml     24
3    ram    cse     56
    name branch  marks
0    anu    cse     34
1  priya    cse     56
2   sita  ai/ml     24
3    ram    cse     56
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      object
 1   branch  4 non-null      object
 2   marks   4 non-null      int64
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes
None
           marks
count   4.000000
mean   42.500000
std    16.114176
min    24.000000
25%    31.500000
50%    45.000000
75%    56.000000
max    56.000000

In [ ]:
print("marks column:")
print(df["marks"])
print("\nbranch and marks:")
print(df[["branch","marks"]])

marks column:
0    34
1    56
2    24
3    56
Name: marks, dtype: int64

branch and marks:
  branch  marks
0    cse     34
1    cse     56
2  ai/ml     24
3    cse     56

In [ ]:
print("first row:")
print(df.iloc[0])
print("first three rows:")
print(df.iloc[:3])

first row:
name      anu
branch    cse
marks      34
Name: 0, dtype: object
first three rows:
    name branch  marks
0    anu    cse     34
1  priya    cse     56
2   sita  ai/ml     24

In [ ]:
print("first 2 rows  and first 2 columns:")
print(df.iloc[0:2,0:2])

first 2 rows  and first 2 columns:
    name branch
0    anu    cse
1  priya    cse

In [ ]:
print("first 3 rows:")
display(df.iloc[0:3])

first 3 rows:

    name branch  marks
0    anu    cse     34
1  priya    cse     56
2   sita  ai/ml     24

In [ ]:
print("\nrows 1 to 3,name and marks:")
display(df.iloc[1:4,0:3])

rows 1 to 3,name and marks:

    name branch  marks
1  priya    cse     56
2   sita  ai/ml     24
3    ram    cse     56

In [ ]:
high_scores=df[df["marks"]>40]
high_scores

    name branch  marks
1  priya    cse     56
3    ram    cse     56

In [ ]:
print("students from cse:")
display(df[df["branch"]=="cse"])

students from cse:

    name branch  marks
0    anu    cse     34
1  priya    cse     56
3    ram    cse     56

In [ ]:
data={
    "name":["asha","bharat","chetan","divya","esha"],
    "branch":["cse","ise","cse","aiml","cse"],
    "marks":[72,91,84,95,68],
    "attendance":[82,94,88,96,75]
}
df=pd.DataFrame(data)
df
display(df["marks"])
display(df["marks"]>80)
display(df[df["marks"]>80])
display(df["attendance"]>85)
display(df[df["attendance"]>85])
display(df.iloc[0:3])
display(df["marks"].max())
display(df["marks"].mean())
display(df[df["branch"]=="cse"])
display(df[(df["marks"]>80) & (df["attendance"]>85)])

0    72
1    91
2    84
3    95
4    68
Name: marks, dtype: int64

0    False
1     True
2     True
3     True
4    False
Name: marks, dtype: bool

     name branch  marks  attendance
1  bharat    ise     91          94
2  chetan    cse     84          88
3   divya   aiml     95          96

0    False
1     True
2     True
3     True
4    False
Name: attendance, dtype: bool

     name branch  marks  attendance
1  bharat    ise     91          94
2  chetan    cse     84          88
3   divya   aiml     95          96

     name branch  marks  attendance
0    asha    cse     72          82
1  bharat    ise     91          94
2  chetan    cse     84          88

95

np.float64(82.0)

     name branch  marks  attendance
0    asha    cse     72          82
2  chetan    cse     84          88
4    esha    cse     68          75

     name branch  marks  attendance
1  bharat    ise     91          94
2  chetan    cse     84          88
3   divya   aiml     95          96

In [ ]:
# @title Default title text
data={
    "name":["asha","bharat","chetan","divya","esha"],
    "branch":["cse","ise","cse","aiml","cse"],
    "marks":[72,91,84,95,68],
    "attendance":[82,94,88,96,75]
}
df=pd.DataFrame(data)
df
display(df["marks"])
display(df["marks"]>80)
display(df[df["marks"]>80])
display(df["attendance"]>85)
display(df[df["attendance"]>85])
display(df.iloc[0:3])
display(df["marks"].max())
display(df["marks"].mean())
display(df[df["branch"]=="cse"])
display(df[(df["marks"]>80) & (df["attendance"]>85)])

0    72
1    91
2    84
3    95
4    68
Name: marks, dtype: int64

0    False
1     True
2     True
3     True
4    False
Name: marks, dtype: bool

     name branch  marks  attendance
1  bharat    ise     91          94
2  chetan    cse     84          88
3   divya   aiml     95          96

0    False
1     True
2     True
3     True
4    False
Name: attendance, dtype: bool

     name branch  marks  attendance
1  bharat    ise     91          94
2  chetan    cse     84          88
3   divya   aiml     95          96

     name branch  marks  attendance
0    asha    cse     72          82
1  bharat    ise     91          94
2  chetan    cse     84          88

95

np.float64(82.0)

     name branch  marks  attendance
0    asha    cse     72          82
2  chetan    cse     84          88
4    esha    cse     68          75

     name branch  marks  attendance
1  bharat    ise     91          94
2  chetan    cse     84          88
3   divya   aiml     95          96